name: CMake

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: scivision/cmake-action@v1

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ./build/tests

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: chat_room
        path: build/chat_room
